import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = { // .tsx  指定了类型 (可以做校验，有类型检查)
  title: "Create Next App",
  description: "Generated by create next app",
};


//相当于react中的  index.html 
// root.render(
// <React.StrictMode> 
//   <App/> 
// </React.StrictMode>
//);
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;//指定了类型
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
